/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: victory_mirosya (https://sketchfab.com/victory_mirosya)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fox-f372c04de44640fbb6a4f9e4e5845c78
Title: Fox
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

import scene from '../assets/3d/fox.glb'

const Fox = ({ currentAnimation, ...props }) => {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(scene)
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    Object.values(actions).forEach((action) =>action.stop());

    if(actions[currentAnimation]) {
        actions[currentAnimation].play();
    }
  }, [actions, currentAnimation])
    

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Jonah's_Enderman_Rigfbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Mesh" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group
                  name="Light"
                  position={[307.625, 190.386, 299.455]}
                  rotation={[1.89, 0.881, -2.045]}
                  scale={100}>
                  <group name="Object_6" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_7" />
                  </group>
                </group>
                <group
                  name="Camera"
                  position={[794.567, 182.179, 3639.037]}
                  rotation={[-2.988, 1.34, 2.913]}
                  scale={100}>
                  <group name="Object_9" />
                </group>
                <group name="Armature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <group name="Object_11">
                    <primitive object={nodes._rootJoint} />
                    <skinnedMesh
                      name="Object_14"
                      geometry={nodes.Object_14.geometry}
                      material={materials.Skin}
                      skeleton={nodes.Object_14.skeleton}
                    />
                    <skinnedMesh
                      name="Object_15"
                      geometry={nodes.Object_15.geometry}
                      material={materials.Eyes}
                      skeleton={nodes.Object_15.skeleton}
                    />
                    <group name="Object_13" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

export default Fox;
